# Generated by Django 4.2.7 on 2023-11-20 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=50)),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('bornAt', models.DateField()),
                ('homeTown', models.CharField(max_length=30)),
                ('avatar', models.ImageField(blank=True, upload_to='uploads/avatars/')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_created=True)),
                ('message', models.CharField(max_length=10000)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='messenger.user')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='messenger.user')),
            ],
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_user', to='messenger.user')),
                ('secondUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_user', to='messenger.user')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_created=True)),
                ('message', models.CharField(max_length=10000)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messenger.user')),
            ],
        ),
    ]
