# Generated by Django 4.2.5 on 2023-11-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0004_rename_message_message_text_alter_friends_firstuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(to='messenger.user'),
        ),
        migrations.DeleteModel(
            name='Friends',
        ),
    ]
