# Generated by Django 4.2.5 on 2023-11-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0004_rename_message_message_text_alter_friends_firstuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
