# Generated by Django 4.2.5 on 2023-12-16 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0014_alter_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='message',
            new_name='text',
        ),
    ]
