# Generated by Django 4.2.5 on 2023-12-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0015_rename_message_feedback_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatars/default.png', upload_to='uploads/avatars/'),
        ),
    ]
