# Generated by Django 4.2.5 on 2023-12-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0016_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='uploads/avatars/default_avatar.png', upload_to='uploads/avatars/'),
        ),
    ]
