# Generated by Django 4.2.5 on 2023-12-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0017_alter_user_avatar'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='chat',
            constraint=models.UniqueConstraint(fields=('firstUser', 'secondUser'), name='unique_firstUser_secondUser'),
        ),
    ]
